sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

before_script:
  - docker-compose -f docker-compose.yml up --build -d

after_script:
  - docker-compose -f docker-compose.yml down
