version: '2.1'

services:
  users-service:
    container_name: users-service
    build: .
    volumes:
      - '.:/app'
    ports:
      - 5000:5000  
    environment: 
      - APP_SETTING=config.DevConfig
